WORKDIR=github.com/lijiaocn/study-Golang/study/binary-only-pkg

install: 
	rm -rf p; cp -rf p_src p
	go build -o ${GOPATH}/pkg/${WORKDIR}/p.a -i ${WORKDIR}/p

build: 
	rm -rf p; cp -rf p_bin p
	go build
