/*
Copyright 2019 The Lijiao Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/lijiaocn/workspace/studys/study-k8s-develop/code-generator/example-1/internal/apis/selfcrd/v1"
	scheme "github.com/lijiaocn/workspace/studys/study-k8s-develop/code-generator/example-1/internal/client/selfcrd/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SelfCRDsGetter has a method to return a SelfCRDInterface.
// A group's client should implement this interface.
type SelfCRDsGetter interface {
	SelfCRDs(namespace string) SelfCRDInterface
}

// SelfCRDInterface has methods to work with SelfCRD resources.
type SelfCRDInterface interface {
	Create(*v1.SelfCRD) (*v1.SelfCRD, error)
	Update(*v1.SelfCRD) (*v1.SelfCRD, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SelfCRD, error)
	List(opts metav1.ListOptions) (*v1.SelfCRDList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SelfCRD, err error)
	SelfCRDExpansion
}

// selfCRDs implements SelfCRDInterface
type selfCRDs struct {
	client rest.Interface
	ns     string
}

// newSelfCRDs returns a SelfCRDs
func newSelfCRDs(c *CrdV1Client, namespace string) *selfCRDs {
	return &selfCRDs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the selfCRD, and returns the corresponding selfCRD object, and an error if there is any.
func (c *selfCRDs) Get(name string, options metav1.GetOptions) (result *v1.SelfCRD, err error) {
	result = &v1.SelfCRD{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("selfcrds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SelfCRDs that match those selectors.
func (c *selfCRDs) List(opts metav1.ListOptions) (result *v1.SelfCRDList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SelfCRDList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("selfcrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested selfCRDs.
func (c *selfCRDs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("selfcrds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a selfCRD and creates it.  Returns the server's representation of the selfCRD, and an error, if there is any.
func (c *selfCRDs) Create(selfCRD *v1.SelfCRD) (result *v1.SelfCRD, err error) {
	result = &v1.SelfCRD{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("selfcrds").
		Body(selfCRD).
		Do().
		Into(result)
	return
}

// Update takes the representation of a selfCRD and updates it. Returns the server's representation of the selfCRD, and an error, if there is any.
func (c *selfCRDs) Update(selfCRD *v1.SelfCRD) (result *v1.SelfCRD, err error) {
	result = &v1.SelfCRD{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("selfcrds").
		Name(selfCRD.Name).
		Body(selfCRD).
		Do().
		Into(result)
	return
}

// Delete takes name of the selfCRD and deletes it. Returns an error if one occurs.
func (c *selfCRDs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("selfcrds").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *selfCRDs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("selfcrds").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched selfCRD.
func (c *selfCRDs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SelfCRD, err error) {
	result = &v1.SelfCRD{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("selfcrds").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
