version: "3"
services:
  echoserver:
    image: googlecontainer/echoserver:1.10
  httprecord:
    image: lijiaocn/http-record:0.0.1
  nginx:
    image: nginx:1.17.9-alpine
    volumes:
      - ./00-nginx/conf:/etc/nginx/conf
      - ./00-nginx/log:/var/log/nginx
      - ./00-nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "9000:8080"
