let g:jekyll_post_extension = '.md'
let g:jekyll_post_template =  [
  \ '---',
  \ 'layout: default',
  \ 'title: "JEKYLL_TITLE"',
  \ 'author: 李佶澳',
  \ 'createdate: "JEKYLL_DATE"',
  \ 'changedate: "JEKYLL_DATE"',
  \ 'categories:',
  \ 'tags:',
  \ 'keywords:',
  \ 'description:',
  \ '---',
  \ '',
  \ '* auto-gen TOC:',
  \ '{:toc}',
  \ '',
  \ '## 说明',
  \ '',
  \ '## 参考',
  \ '',
  \ '1. [文献][1]',
  \ '',
  \ '[1]: 1.com "文献1',
  \ '']
