swagger: '2.0'
info:
    title: icanbuy restful apis
    description: icanbuy restful apis
    termsOfService: no
    contact: 
        name: icanbuy
        url: icanbuy
        email: icanbuy
    license: 
        name: no
        url: no
    version: 1.0
host: api.icanbuy.cn 
basePath: /v1.0
schemes:
    - http
    - https
consumes:
    - application/json
produces:
    - application/json
paths:
    /user:
        $ref: './paths/user.yaml#/'
definitions:
    UserInfo:
        $ref: './definitions/UserInfo.yaml#/'
parameters:
responses:
    NotFound:
        $ref: './responses/NotFound.yaml#/'
    UnExpected:
        $ref: './responses/UnExpected.yaml#/'
    Success:
        $ref: './responses/Success.yaml#/'
securityDefinitions:
    Token:
        type: apiKey
        description: Request Token
        name: Token       
        in: header
security:
    - Token: []
tags:
    - user
externalDocs:
