/*
Copyright 2019 The Lijiao Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	selfcrdv1 "github.com/lijiaocn/workspace/studys/study-k8s-develop/code-generator/example-1/internal/apis/selfcrd/v1"
	versioned "github.com/lijiaocn/workspace/studys/study-k8s-develop/code-generator/example-1/internal/client/selfcrd/clientset/versioned"
	internalinterfaces "github.com/lijiaocn/workspace/studys/study-k8s-develop/code-generator/example-1/internal/client/selfcrd/informers/externalversions/internalinterfaces"
	v1 "github.com/lijiaocn/workspace/studys/study-k8s-develop/code-generator/example-1/internal/client/selfcrd/listers/selfcrd/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SelfCRDInformer provides access to a shared informer and lister for
// SelfCRDs.
type SelfCRDInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SelfCRDLister
}

type selfCRDInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSelfCRDInformer constructs a new informer for SelfCRD type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSelfCRDInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSelfCRDInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSelfCRDInformer constructs a new informer for SelfCRD type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSelfCRDInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().SelfCRDs(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().SelfCRDs(namespace).Watch(options)
			},
		},
		&selfcrdv1.SelfCRD{},
		resyncPeriod,
		indexers,
	)
}

func (f *selfCRDInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSelfCRDInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *selfCRDInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&selfcrdv1.SelfCRD{}, f.defaultInformer)
}

func (f *selfCRDInformer) Lister() v1.SelfCRDLister {
	return v1.NewSelfCRDLister(f.Informer().GetIndexer())
}
